from __future__ import annotations

from typing import Sequence


def _format_number(value: float | int) -> str:
    """Format numbers for Lua while keeping integers compact."""
    as_float = float(value)
    if as_float.is_integer():
        return str(int(as_float))
    return f"{as_float:.3f}".rstrip("0").rstrip(".")


def build_studs_data_lua(studs: Sequence[dict[str, float]]) -> str:
    """Build a Lua data file that defines the dynamic studs table."""
    studs_lua = ",\n".join(
        f"    {{x={_format_number(stud['x'])}, y={_format_number(stud['y'])}}}" for stud in studs
    )

    return f"""-- Auto-generated by WeldFlex.
-- Data payload consumed by base program studCycle.lua.

studs = {{
{studs_lua}
}}
"""
