from __future__ import annotations

import math
from typing import Sequence

MAX_OFFSET_MM = 2000.0
MAX_CLEARANCE_MM = 500.0


def _format_number(value: float | int) -> str:
    as_float = float(value)
    if as_float.is_integer():
        return str(int(as_float))
    return f"{as_float:.3f}".rstrip("0").rstrip(".")


def validate_studs(studs: Sequence[dict[str, float]]) -> None:
    if not studs:
        raise ValueError("No stud coordinates provided.")
    for i, stud in enumerate(studs, start=1):
        x = stud.get("x")
        y = stud.get("y")
        if x is None or y is None:
            raise ValueError(f"Stud {i}: missing x or y value.")
        if not math.isfinite(x) or not math.isfinite(y):
            raise ValueError(f"Stud {i}: coordinates must be finite numbers.")
        if abs(x) > MAX_OFFSET_MM or abs(y) > MAX_OFFSET_MM:
            raise ValueError(
                f"Stud {i}: ({x}, {y}) mm exceeds the ±{int(MAX_OFFSET_MM)} mm limit — check for a data-entry error."
            )


def validate_zerozero_joints(zerozero_joints: Sequence[float] | None) -> list[float]:
    if zerozero_joints is None:
        raise ValueError("Missing zerozero joint positions. Re-run work area calibration and record pin 1.")
    if len(zerozero_joints) != 6:
        raise ValueError("zerozero joint positions must contain exactly 6 values.")
    parsed = [float(value) for value in zerozero_joints]
    if any(not math.isfinite(value) for value in parsed):
        raise ValueError("zerozero joint positions must be finite numbers.")
    return parsed


def validate_zerozero_tcp(zerozero_tcp: Sequence[float] | None) -> list[float]:
    if zerozero_tcp is None:
        raise ValueError("Missing zerozero TCP pose. GetForwardKin failed — check robot connection.")
    if len(zerozero_tcp) != 6:
        raise ValueError("zerozero TCP pose must contain exactly 6 values (x,y,z,rx,ry,rz).")
    parsed = [float(value) for value in zerozero_tcp]
    if any(not math.isfinite(value) for value in parsed):
        raise ValueError("zerozero TCP pose must be finite numbers.")
    return parsed


def build_studs_data_lua(
    studs: Sequence[dict[str, float]],
    clearance_z_mm: float = 50.0,
    zerozero_joints: Sequence[float] | None = None,
    zerozero_tcp: Sequence[float] | None = None,
) -> str:
    validate_studs(studs)
    joints = validate_zerozero_joints(zerozero_joints)
    tcp = validate_zerozero_tcp(zerozero_tcp)
    if not math.isfinite(clearance_z_mm) or clearance_z_mm < 5.0 or clearance_z_mm > MAX_CLEARANCE_MM:
        raise ValueError(f"clearance_z_mm must be between 5 and {int(MAX_CLEARANCE_MM)} mm.")
    stud_rows: list[str] = []
    for i, stud in enumerate(studs, start=1):
        row = f"    {{x={_format_number(stud['x'])}, y={_format_number(stud['y'])}"
        wf_value = stud.get("wf")
        if wf_value is not None:
            if not isinstance(wf_value, Sequence) or len(wf_value) != 6:
                raise ValueError(f"Stud {i}: wf must contain exactly 6 values.")
            parsed_wf = [float(value) for value in wf_value]
            if any(not math.isfinite(value) for value in parsed_wf):
                raise ValueError(f"Stud {i}: wf must be finite numbers.")
            wf_lua = ", ".join(_format_number(value) for value in parsed_wf)
            row += f", wf={{{wf_lua}}}"
        joints_value = stud.get("joints")
        if joints_value is not None:
            if not isinstance(joints_value, Sequence) or len(joints_value) != 6:
                raise ValueError(f"Stud {i}: joints must contain exactly 6 values.")
            parsed_joints = [float(value) for value in joints_value]
            if any(not math.isfinite(value) for value in parsed_joints):
                raise ValueError(f"Stud {i}: joints must be finite numbers.")
            joints_lua = ", ".join(_format_number(value) for value in parsed_joints)
            row += f", joints={{{joints_lua}}}"
        row += "}"
        stud_rows.append(row)

    studs_lua = ",\n".join(stud_rows)
    joints_lua = ", ".join(_format_number(v) for v in joints)
    tcp_lua = ", ".join(_format_number(v) for v in tcp)

    return f"""-- Auto-generated by WeldFlex.
-- Data payload consumed by base program studCycle.lua.

zerozeroJoints = {{{joints_lua}}}

zerozeroWF = {{{tcp_lua}}}

clearance_z_mm = {_format_number(clearance_z_mm)}

studs = {{
{studs_lua}
}}
"""
